
class Person
    @@first_names = ["Ermelindaf",
    "Kacyf",
    "Altaf",
    "Shakitaf",
    "Reitaf",
    "Jovitaf",
    "Lucreciaf",
    "Cedricm",
    "Leonoraf",
    "Latoyaf",
    "Lacym",
    "Jodif",
    "Barbaraf",
    "Reyesm",
    "Dessief",
    "Josefm",
    "Kentm",
    "Jaquelinef",
    "Goldief",
    "Rashadm",
    "Treym",
    "Astridf",
    "Kaceyf",
    "Rheaf",
    "Rosief",
    "Krystenf",
    "Starf",
    "Jinf",
    "Patsyf",
    "Juliusm",
    "Jolinef",
    "Norbertom",
    "Ingridf",
    "Jaymief",
    "Ardisf",
    "Luigim",
    "Rosef",
    "Alyshaf",
    "Neomaf",
    "Almaf",
    "Eviaf",
    "Carolinef",
    "Lorrainef",
    "Lemuelm",
    "Aikof",
    "Leotaf",
    "Douglasm",
    "Rosalinef",
    "Shanif",
    "Lateshaf"]

    @@last_names = ["Mosser",
    "Facey",
    "Sherry",
    "Escaante",
    "Nolte",
    "Ostrem",
    "Cothran",
    "Asay",
    "Carone",
    "Dangerfield",
    "Barto",
    "Girardi",
    "Morais",
    "Schuette",
    "Bramble",
    "Vogelsang",
    "Pillai",
    "Voss",
    "Kivi",
    "Ashley",
    "Kary",
    "Spagnuolo",
    "Speers",
    "Dinh",
    "Marrs",
    "Bos",
    "Arocho",
    "Colangelo",
    "Glines",
    "Livers",
    "Witkowski",
    "Forrest",
    "Naslund",
    "Albus",
    "Bankhead",
    "Thiede",
    "Munk",
    "Herrin",
    "Rosenblum",
    "Lemon",
    "Phifer",
    "Gaylord",
    "Rolan",
    "Stehlik",
    "Corpuz",
    "Tomasek",
    "Sammet",
    "Matheny",
    "Buchler",
    "Almonte"]

    attr_accessor :first_name, :last_name, :age, :gender

    def initialize()
        random_num = Random.rand(@@first_names.length-1)
        @first_name = @@first_names[random_num]
        @gender = @first_name[-1]
        @first_name = @first_name.chop
        @age = Random.rand(110)
        @last_name = @@last_names[Random.rand(@@last_names.length-1)] 
    end

    def name()
        return "#{first_name} #{last_name}"
    end
end

